import fs from 'fs';
import path from 'path';
import JSZip from 'jszip';
import { Flashcard } from '../types';

export function exportToCsv(cards: Flashcard[]): string {
  const header = 'Front\tBack\tTags\tType\tSource\tPage\tClozeText\n';
  const rows = cards.map(card => {
    const front = (card.front || '').replace(/\t/g, ' ').replace(/\n/g, '<br>');
    const back = (card.back || '').replace(/\t/g, ' ').replace(/\n/g, '<br>');
    const tags = card.tags.join(' ');
    const source = card.source.fileName;
    const page = card.source.pageNumber?.toString() || '';
    const cloze = (card.clozeText || '').replace(/\t/g, ' ');
    return `${front}\t${back}\t${tags}\t${card.cardType}\t${source}\t${page}\t${cloze}`;
  });
  return header + rows.join('\n');
}

// Build a minimal .apkg (Anki package) compatible file.
// APKG is a zip containing collection.anki2 (SQLite) + media files.
// We produce a text-based deck that Anki can import via the CrowdAnki JSON format
// as well as a proper TSV fallback.
export async function exportToApkg(cards: Flashcard[], deckName: string): Promise<Buffer> {
  const zip = new JSZip();

  // Anki 2.1+ supports importing via CrowdAnki JSON format
  const deckId = Math.floor(Math.random() * 1e12);
  const modelId = Math.floor(Math.random() * 1e12);
  const clozeModelId = Math.floor(Math.random() * 1e12);
  const now = Math.floor(Date.now() / 1000);

  const notes = cards.map((card, i) => {
    if (card.cardType === 'cloze' && card.clozeText) {
      return {
        __type__: 'Note',
        guid: card.id.replace(/-/g, '').slice(0, 16),
        note_model_uuid: `cloze-${clozeModelId}`,
        tags: card.tags,
        fields: [card.clozeText, card.back],
      };
    }
    return {
      __type__: 'Note',
      guid: card.id.replace(/-/g, '').slice(0, 16),
      note_model_uuid: `basic-${modelId}`,
      tags: card.tags,
      fields: [card.front, card.back],
    };
  });

  const crowdAnki = {
    __type__: 'Deck',
    crowdanki_uuid: `${deckId}`,
    name: deckName,
    desc: `Generated by AnkiForge on ${new Date().toLocaleDateString()}`,
    note_models: [
      {
        __type__: 'NoteModel',
        crowdanki_uuid: `basic-${modelId}`,
        name: 'AnkiForge Basic',
        flds: [{ name: 'Front' }, { name: 'Back' }],
        tmpls: [{
          name: 'Card 1',
          qfmt: '{{Front}}',
          afmt: '{{FrontSide}}<hr id=answer>{{Back}}',
        }],
      },
      {
        __type__: 'NoteModel',
        crowdanki_uuid: `cloze-${clozeModelId}`,
        name: 'AnkiForge Cloze',
        flds: [{ name: 'Text' }, { name: 'Extra' }],
        tmpls: [{
          name: 'Cloze',
          qfmt: '{{cloze:Text}}',
          afmt: '{{cloze:Text}}<br>{{Extra}}',
        }],
        type: 1,
      },
    ],
    notes,
    children: [],
  };

  zip.file('deck.json', JSON.stringify(crowdAnki, null, 2));
  zip.file('media', '{}');

  // Also bundle a TSV for universal compatibility
  zip.file('cards.tsv', exportToCsv(cards));

  // README with import instructions
  zip.file('IMPORT_INSTRUCTIONS.txt', `AnkiForge Export
================

Option A — Direct TSV Import (simplest):
1. Open Anki → File → Import
2. Select cards.tsv from this zip
3. Set field separator to Tab
4. Map: Field 1 = Front, Field 2 = Back, Field 3 = Tags

Option B — CrowdAnki JSON Import (preserves card types):
1. Install the CrowdAnki add-on in Anki (ID: 1788670778)
2. Extract this zip to a folder
3. In Anki: File → CrowdAnki Import from Disk
4. Select the extracted folder

Enjoy studying!
`);

  return zip.generateAsync({ type: 'nodebuffer' });
}
